### ISSUE TITLE
make_libraries.py fails due to missing permission

### ISSUE THREAD

**Issue by bit-pirate** [ros-drivers/rosserial#39] opened 2013-04-15 00:17 UTC
I just installed the rosserial and rosserial-arduino debs in my Groovy/Precise 64bit environment.

Unfortunately, make_libraries doesn't work due to missing permissions:

```
~/sketchbook/libraries$ rosrun rosserial_arduino make_libraries.py .

Exporting to .
Traceback (most recent call last):
  File "/opt/ros/groovy/share/rosserial_arduino/make_libraries.py", line 88, in <module>
    rosserial_client_copy_files(rospack, rosserial_arduino_dir+"/src/ros_lib/")
  File "/opt/ros/groovy/lib/python2.7/dist-packages/rosserial_client/make_library.py", line 580, in rosserial_client_copy_files
    shutil.copy(mydir+"/src/ros_lib/"+f, path+f)
  File "/usr/lib/python2.7/shutil.py", line 117, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/opt/ros/groovy/share/rosserial_arduino/src/ros_lib/duration.cpp'
```

I have tried it with sudo, but that doesn't help either (no rosrun command found).

Did I do sth wrong or is this a bug?

**Comment by mikeferguson** [comment] 2013-04-15 00:27
It is currently a bug, that we didn't catch until we released debs (only happens with debs). Basically we can't use shutils... but I haven't found time to rewrite and test it all the way through to debs yet.

**Comment by bit-pirate** [comment] 2013-04-15 01:38
I see. Well, it works when compiling from source.
Maybe we should add a note to the ROS wiki tutorial.

**Comment by tompe17** [comment] 2013-07-12 00:50
Yes, a note in the ROS Wiki Tutorial would have been nice since this problem seems not to be fixed yet and I trusted the tutorials to be correct...

**Comment by PaulBouchier** [comment] 2013-07-16 04:18
@tompe17 sorry you ran into that. I've updated the wiki tutorial with a prominent warning.

**Comment by PaulBouchier** [comment] 2013-09-10 09:48
@mikeferguson I just tried this on hydro and it worked fine. We had previously discussed that we don't know why this fails, and now I find I'm unable to reproduce it. This file: 
IOError: [Errno 13] Permission denied: '/opt/ros/hydro/share/rosserial_arduino/src/ros_lib/duration.cpp' doesn't exist
but duration.cpp is in sketchbook/libraries/ros_lib

I'm thinking about removing the note from the tutorials saying it doesn't work. Thoughts?

The other thing that seems wrong in the wiki is you have to install rosserial then rosserial_arduino, whereas it just tells you to install rosserial. Should it in fact tell you to install rosserial_arduino (or rosserial_embeddedlinux)?

**Comment by mikeferguson** [comment] 2013-09-10 11:06
@PaulBouchier Hmm, so everything works fine in my hydro install -- and looking at it, there are changes to that function that are after 0.4.4 -- so we should probably push a new groovy 0.4.5 release to fix this in groovy (there are some os.makedirs that you added that were never released into groovy) (note: there is already a mostly broken 0.4.5 tag, so you should replace that -- it does not include the code after 0.4.4, and the package.xmls are all wrong)

I think as soon as a new groovy release is out, we can safely remove the note (and for now it could be updated to say all is well in hydro).

RE: installing rosserial_arduino vs. rosserial, that is probably just out of date -- prior to catkinization, rosserial metastackagethingy included all clients -- now, you should install rosserial_X for each X-platform you want to use, which will then pull in all the underlying rosserial stuff -- so yes, update the wiki anywhere it says to install just rosserial

**Comment by mikeferguson** [comment] 2013-09-10 11:15
It appears the fix was in this commit: https://github.com/ros-drivers/rosserial/commit/178f79674b9e1434520a996437f8033f614401d4

I have absolutely no idea how I originally messed that up so badly -- I'm guessing that I ended running it once  (which copied all the rosserial_client stuff into my non-installed rosserial_arduino directories, and then when I did a second make_libraries I got everything I needed... that is a really stupid bug to have, and the whole time I was sure it was a problem in shutil.....).

You want me to push a new groovy release to make this go away forever? And then we can close this stupid ticket....

**Comment by PaulBouchier** [comment] 2013-09-10 12:52
Great that you have an explanation - thanks. Why don't I do the new groovy release - I'm already getting hazy on how to do a release and this will motivate me to document it.

**Comment by PaulBouchier** [comment] 2013-09-22 14:26
When you say the package.xmls are wrong, I think it's the maintainer emails and version that's wrong, correct?

Is this what I should do?
- delete 0.4.5 tag
- checkout groovy-devel head
- fix the package .xml maintainer fields. Version will be fixed by catkin_prepare_release
- There are no changelog.rst files - don't run the catkin_generate_changelogs & catkin_tag_changelog scripts, since there weren't changelogs in groovy. Thoughts?
  -tag with 0.4.5
- do a release

I'm concerned about the 0.4.5 tag that's on the github repo. How to get rid of it, or update it with the new 0.4.5 tag?

**Comment by mikeferguson** [comment] 2013-09-23 01:03
I'm guessing catkin_prepare_release will even overwrite the 0.4.5 tag. Basically the existing tag is actually to something that is slightly later than 0.4.4, but not quite 0.4.5 (the revision in the package.xml is still 0.4.4, and there the cmake changes that make the installed stuff work are missing).

**Comment by mikeferguson** [comment] 2014-10-26 05:24
Just tested, and make_libraries from debs works, so I'm not sure when we fixed this, but it is fixed...

**Closed as completed by mikeferguson** 2014-10-26 05:24 UTC
