### ISSUE TITLE
Running rosrun rosserial_arduino make_libraries.py . fails to generate libraries

### ISSUE THREAD

**Issue by eyphka** [ros-drivers/rosserial#161] opened 2015-02-11 22:03 UTC
Running rosrun rosserial_arduino make_libraries.py . inside sketchbook/libraries as per http://wiki.ros.org/rosserial_arduino/Tutorials/Arduino%20IDE%20Setup results in missing libraries: 

**\* Warning, failed to generate libraries for the following packages: ***
    geometry_msgs
    sensor_msgs
    shape_msgs

**Comment by mikeferguson** [comment] 2015-02-11 22:05
Duplicate of #158

**Comment by mikepurvis** [comment] 2015-03-11 12:10
Fixed by #162.

**Closed as completed by mikepurvis** 2015-03-11 12:10 UTC
