### ISSUE TITLE
Creation of subscriber failed: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by tonybaltovski** [ros-drivers/rosserial#76] opened 2013-10-01 17:43 UTC
After pulling to the latest version of rosserial - hydro-devel, any time I run the serial_node, I get the following error: "Creation of subscriber failed: unpack requires a string argument of length 4".  I have recompiled everything (workspace and ros_lib) but nothing seems to work. Did anything change that I need to update?

**Comment by PaulBouchier** [comment] 2013-10-02 02:52
Looking into it. I just released 0.5.3. It passed my local testing, the hello world app works, but Tongtybj ran into a problem and now I see the pubsub example doesn't work and you have a problem. Something broke.Trying to find it. I'll post a fix here - this is my highest rosserial priority.

**Comment by tonybaltovski** [comment] 2013-10-02 02:58
What hardware did you test on?

**Comment by PaulBouchier** [comment] 2013-10-02 04:14
ATMega328. But it's broken on certain sketches. I think you'll find that the Hello World example works, but pubsub example doesn't.

**Comment by tonybaltovski** [comment] 2013-10-02 04:18
The Hello World example does work but that sketch does not have a subscriber.  Anything with a subscriber that I tried did not work.

**Comment by stebl** [comment] 2013-10-04 12:48
Hi, I've run into the same problem.
On my end, it seems to be related to having multiple subscribers/publishers.  A single pub works, adding another pub/sub breaks it.  I've documented more of what I've seen in the forum below

http://answers.ros.org/question/87016/rosserial-multiple-publishers/

**Comment by PaulBouchier** [comment] 2013-10-13 20:23
This is a duplicate of issue 74 filed by @tongtybj

The problem may be an incorrect length field

# This program fails on arduino but works on a 32-bit platform (ARM-based VEXPro):

/*
- rosserial Subscriber Example
- Blinks an LED on callback
  */

#include <ros.h>
#include <std_msgs/Empty.h>
#include <std_msgs/Int8.h>

ros::NodeHandle nh;

void messageCb1( const std_msgs::Empty& toggle_msg){
  digitalWrite(13, HIGH-digitalRead(13)); // blink the led
}
ros::Subscriber<std_msgs::Empty> sub1("sub1", &messageCb1 );

//void messageCb2( const std_msgs::Empty& toggle_msg){
//  digitalWrite(13, HIGH-digitalRead(13)); // blink the led
//}
//ros::Subscriber<std_msgs::Empty> sub2("sub2", &messageCb2 );

std_msgs::Int8 int_pub1;
ros::Publisher pub1("pub1", &int_pub1);

//std_msgs::Int8 int_pub2;
//ros::Publisher pub2("pub2", &int_pub2);

void setup()
{
  pinMode(13, OUTPUT);
  nh.initNode();
  nh.subscribe(sub1);
//  nh.subscribe(sub2);
  nh.advertise(pub1);
//  nh.advertise(pub2);
}

void loop()
{
  nh.spinOnce();
  delay(1);
}

# 

The two subscription messages received by rosserai_python are:

std_msgs/Int8 27ffa0c9c4b8fb8492252bcad9e5c57b
0x7d 0x0 0x4 0x0 0x0 0x0 0x70 0x75 0x62 0x31 0xd 0x0 0x0 0x0 0x73 0x74 0x64 0x5f 0x6d 0x73 0x67 0x73 0x2f 0x49 0x6e 0x74 0x38 0x20 0x0 0x0 0x0 0x32 0x37 0x66 0x66 0x61 0x30 0x63 0x39 0x63 0x34 0x62 0x38 0x66 0x62 0x38 0x34 0x39 0x32 0x32 0x35 0x32 0x62 0x63 0x61 0x64 0x39 0x65 0x35 0x63 0x35 0x37 0x62 0x18 0x1 0x0 0x0
[INFO] [WallTime: 1381399915.696481] Note: publish buffer size is 280 bytes
[INFO] [WallTime: 1381399915.698027] Setup publisher on pub1 [std_msgs/Int8]
dsub1std_msgs/Empty 2d41d8cd98f00b204e9800998ecf8427e
0x64 0x0 0x4 0x0 0x0 0x0 0x73 0x75 0x62 0x31 0xe 0x0 0x0 0x0 0x73 0x74 0x64 0x5f 0x6d 0x73 0x67 0x73 

0x2f 0x45 0x6d 0x70 0x74 0x79 0x20 0x0 0x0 0x32 0x64 0x34 0x31 0x64 0x38 0x63 0x64 0x39 0x38 0x66 0x30
                              ^^^^^^^^^^^^^^^^^^
 0x30 0x62 0x32 0x30 0x34 0x65 0x39 0x38 0x30 0x30 0x39 0x39 0x38 0x65 0x63 0x66 0x38 0x34 0x32 0x37 0x65 0x18 0x1 0x0 0x0

# [ERROR] [WallTime: 1381399915.701501] Creation of subscriber failed: unpack requires a string argument of length 4

The second message has an incorrect length for the md5sum. The '2' printed at the start of the md5sum is corruption, and is highlighted in the hex string above with carets. The high byte of the md5sum string length is getting set to 0x32, which prints as a 2 at the start of the md5sum.

Why?

The specific code that looks faulty is in std_msgs/String.h:

# 

  class String : public ros::Msg
  {
    public:
      char \* data;

```
virtual int serialize(unsigned char *outbuffer) const
{
  int offset = 0;
  size_t length_data = strlen( (const char*) this->data);
  memcpy(outbuffer + offset, &length_data, sizeof(size_t));
  offset += 4;
  memcpy(outbuffer + offset, this->data, length_data);
  offset += length_data;
  return offset;
}
```

# 

Note how offset is incremented by 4 after copying length_data into the message. A sketch which prints sizeof(size_t) reports it as length
2 bytes, meaning 2 bytes are uninitialized, and certain programs would leave junk on the stack in those places, and potentially cause the
failure described.

I attempted to prove the theory by editing ~/sketchbook/libraries/ros_lib/std_msgs/String.h and inserting a bzero() before offset+=4,
but no change in symptoms. Then I destroyed the compilability of the file by inserting "foo" in the code, and it still compiles.
Apparently the compiler isn't using that file. But where is the file it's using? 

# 

Compiler output

avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/home/bouchier/sketchbook/libraries/ros_lib /tmp/build1944916245079886478.tmp/TongsTest2.cpp -o/tmp/build1944916245079886478.tmp/TongsTest2.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/home/bouchier/sketchbook/libraries/ros_lib -I/home/bouchier/sketchbook/libraries/ros_lib/utility /home/bouchier/sketchbook/libraries/ros_lib/duration.cpp -o/tmp/build1944916245079886478.tmp/ros_lib/duration.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard -I/home/bouchier/sketchbook/libraries/ros_lib -I/home/bouchier/sketchbook/libraries/ros_lib/utility /home/bouchier/sketchbook/libraries/ros_lib/time.cpp -o/tmp/build1944916245079886478.tmp/ros_lib/time.cpp.o 
avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/wiring_pulse.c -o/tmp/build1944916245079886478.tmp/wiring_pulse.c.o 
avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/wiring_shift.c -o/tmp/build1944916245079886478.tmp/wiring_shift.c.o 
avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/WInterrupts.c -o/tmp/build1944916245079886478.tmp/WInterrupts.c.o 
avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/wiring_digital.c -o/tmp/build1944916245079886478.tmp/wiring_digital.c.o 
avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/wiring.c -o/tmp/build1944916245079886478.tmp/wiring.c.o 
avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/wiring_analog.c -o/tmp/build1944916245079886478.tmp/wiring_analog.c.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp -o/tmp/build1944916245079886478.tmp/Tone.cpp.o 
/usr/share/arduino/hardware/arduino/cores/arduino/Tone.cpp:108:45: warning: only initialized variables can be placed into program memory area
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/CDC.cpp -o/tmp/build1944916245079886478.tmp/CDC.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/USBCore.cpp -o/tmp/build1944916245079886478.tmp/USBCore.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/WMath.cpp -o/tmp/build1944916245079886478.tmp/WMath.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/WString.cpp -o/tmp/build1944916245079886478.tmp/WString.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/HID.cpp -o/tmp/build1944916245079886478.tmp/HID.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/main.cpp -o/tmp/build1944916245079886478.tmp/main.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/Print.cpp -o/tmp/build1944916245079886478.tmp/Print.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/Stream.cpp -o/tmp/build1944916245079886478.tmp/Stream.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp -o/tmp/build1944916245079886478.tmp/IPAddress.cpp.o 
In file included from /usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.cpp:3:0:
/usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.h: In member function ‘IPAddress::operator uint32_t()’:
/usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.h:51:55: warning: dereferencing type-punned pointer will break strict-aliasing rules
/usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.h: In member function ‘bool IPAddress::operator==(const IPAddress&)’:
/usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.h:52:75: warning: dereferencing type-punned pointer will break strict-aliasing rules
/usr/share/arduino/hardware/arduino/cores/arduino/IPAddress.h:52:108: warning: dereferencing type-punned pointer will break strict-aliasing rules
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/new.cpp -o/tmp/build1944916245079886478.tmp/new.cpp.o 
avr-g++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/standard /usr/share/arduino/hardware/arduino/cores/arduino/HardwareSerial.cpp -o/tmp/build1944916245079886478.tmp/HardwareSerial.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/wiring_pulse.c.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/wiring_shift.c.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/WInterrupts.c.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/wiring_digital.c.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/wiring.c.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/wiring_analog.c.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/Tone.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/CDC.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/USBCore.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/WMath.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/WString.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/HID.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/main.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/Print.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/Stream.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/IPAddress.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/new.cpp.o 
avr-ar rcs /tmp/build1944916245079886478.tmp/core.a /tmp/build1944916245079886478.tmp/HardwareSerial.cpp.o 
avr-gcc -Os -Wl,--gc-sections -mmcu=atmega328p -o /tmp/build1944916245079886478.tmp/TongsTest2.cpp.elf /tmp/build1944916245079886478.tmp/TongsTest2.cpp.o /tmp/build1944916245079886478.tmp/ros_lib/duration.cpp.o /tmp/build1944916245079886478.tmp/ros_lib/time.cpp.o /tmp/build1944916245079886478.tmp/core.a -L/tmp/build1944916245079886478.tmp -lm 
avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 /tmp/build1944916245079886478.tmp/TongsTest2.cpp.elf /tmp/build1944916245079886478.tmp/TongsTest2.cpp.eep 
avr-objcopy -O ihex -R .eeprom /tmp/build1944916245079886478.tmp/TongsTest2.cpp.elf /tmp/build1944916245079886478.tmp/TongsTest2.cpp.hex 
Binary sketch size: 9454 bytes (of a 30720 byte maximum)

# 

The include path seems to pull from 
-I/home/bouchier/sketchbook/libraries/ros_lib 

I've tried stopping & restarting Arduino, but can't get it to pick up my changes. Any suggestions welcome

#

**Comment by PaulBouchier** [comment] 2013-10-13 20:26
ok - that wasn't it. It may still be a bug, but it's not this bug - the sketch doesn't use std_msgs/String.h. Putting a serialSoftware UART print in TopicInfo.h causes the bug to disappear. Must be position-dependent corruption happening somewhere.

**Comment by mikeferguson** [comment] 2013-10-13 21:30
@PaulBouchier try the following: change size_t to uint32_t and see if it works. And then we should actually change to uint32_t, because the size of size_t is not defined in the C specification (it appears the size_t change was part of Lorenzo's updates to make_libraries.py). We really should be using uint32_t -- as that is what is specified by the ROS serialization. size_t may be platform dependent.

If you're looking for a quick experiment as to why this works with SoftwareSerial, try including <stddef.h> as apparently it changes the size of size_t: http://www.avrfreaks.net/index.php?name=PNphpBB2&file=viewtopic&t=29122

**Comment by PaulBouchier** [comment] 2013-10-14 08:52
Thanks for the assist @mikeferguson - it helped to see where the bug got introduced. I've checked in the fix to use uint32_t instead of size_t, and I'll do a new release of debs for just this fix, so we get back to a stable version before I look at other issues.

The problem actually went away on my Arduino for both the programs provided by @tongtybj and @stebl and I can no longer reproduce it. This despite rebuilding ros_lib. While concerning, this is not totally unexpected, since the fault involved uninitialized data, which can come up in any random state. I guess I count myself lucky that it was reproducible for long enough to identify the problem.

@tongtybj and @stebl please pull the top of tree and check that it fixes the problem you reported

**Closed as completed by PaulBouchier** 2013-10-14 08:52 UTC

**Comment by PaulBouchier** [comment] 2013-10-14 09:04
Note: you will have to re-build ros_lib (rm -r ros_lib; rosrun rosserial_arduino make_libraries.py .) to get the fix.

**Comment by stebl** [comment] 2013-10-15 00:29
Confirmed working :)

**Comment by tonybaltovski** [comment] 2013-10-15 23:00
Also works for me. Thanks.

**Comment by zchen99** [comment] 2016-01-22 07:04
Hi Paul,
I met this issue on MIPS arch, due to endianess?

https://github.com/ros-drivers/rosserial/issues/109

Could you give some comments here? 

Thanks.
